version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    volumes:
      - postgres:/var/lib/postgresql/data

  nest-app:
    image: nestjs_api_prod
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 9229:9229
    env_file:
      - .env.prod
    volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
    restart: unless-stopped
    
networks: 
  testdev:
volumes:
  postgres:
    name: nest-db
  